### ISSUE TITLE
Emojis in markdown view

### ISSUE THREAD

**Issue by Njoselson** [sn-extensions/minimal-markdown-editor#18] opened 2019-12-13 20:38 UTC
I would love to have emojis that could be displayed with the : word syntax like slack and github user.

Does this sound like something that would be nice? It would make my notes a lot more fun! 😝

**Comment by bryvin** [comment] 2019-12-17 15:48
This would be nice to offer but unfortunately is tricky for us to implement for each of the SN editors. They are all different sources and would have to be updated to allow for this behavior. Since most of the SN extensions are open-source 3rd party editors we also do not have the control over each of their functions beyond the customization they provide by default.

Editors however can be created by the community and be made to support any feature that is desired by the user. If you'd like to learn more about creating your own extensions you can visit the docs: https://docs.standardnotes.org/extensions/intro-to-extensions

**Comment by bryvin** [comment] 2019-12-17 16:12
Going to close this as it's not a bug with the editor. Thank you for the suggestion though!

**Closed by bryvin** 2019-12-17 16:12 UTC

**Comment by MorgothSauron** [comment] 2019-12-17 17:10
Personally I prefer the way SN it is. No need for "fancy" emojis. This will help the app remain simple.
